### ISSUE TITLE
setsockopt IP_TRANSPARENT error while redirecting connection to HTTPS server, with working transparent by protocol

### ISSUE THREAD

**Issue by SGNoc** [yrutschle/sslh#289] opened 2021-05-04 20:51 UTC
I've compiled and setup the latest code release to use transparent by protocol for my application. I have the transparent by protocol working, but am getting an error with the HTTPS connection.  The SSH connection seems to be working with the transparent mode off. Am I missing a configuration setting that would fix this?

Here is the SSLH log:

```
ssh addr: <sslh/web server IP>:222. libwrap service: ssh log_level: 1 family 2 2 [] [fork] []
tls addr: <ssh server IP>:4443. libwrap service: https log_level: 1 family 2 2 [] [fork] [transparent]
timeout: 2
on-timeout: ssh
Listening to:
3:	<sslh/web server IP>:https	[]
sslh-fork head-2021-05-04 started
turning into sslh
capabilities: =
accepted fd 5
**** writing deferred on fd -1
probing for ssh
probed for ssh: PROBE_NEXT
probing for tls
probed for tls: PROBE_MATCH
connecting to <sslh/web server IP>:4443 family 2 len 16
common.c:270:setsockopt IP_TRANSPARENT: Operation not permitted

```

I have tried setting the capabilities with: `setcap cap_net_bind_service,cap_net_admin+pe /usr/sbin/sslh` but it is still giving the same error. I've also tried running with the user as root in the cfg file.

Here is my cfg:
```
verbose: 1;
foreground: true;
inetd: false;
numeric: false;
timeout: 2;
user: "sslh";
pidfile: "/var/run/sslh.pid";

listen:
(
    { host: "<sslh/web server IP>"; port: "443"; }
);

protocols:
(
     { name: "ssh"; service: "ssh"; host: "<ssh server>"; port: "222"; fork: true; transparent: false; },
     { name: "tls"; service: "https"; host: "<sslh/web server IP>"; port: "4443"; fork: true; transparent: true; }
);
```

**Comment by yrutschle** [comment] 2021-05-05 05:46
> The SSH connection seems to be working with the transparent mode off.

That part is normal as you set `transparent: false` in the ssh entry.

What's not clear here is whether you had transparent proxy working at all, ever. Does it work if you set it globally?
I have seen setsockopt fail on kernels which do not support transparent proxy: IIRC you need to have a specific module loaded (ip_tproxy or something like that).

**Comment by SGNoc** [comment] 2021-05-05 16:44
> What's not clear here is whether you had transparent proxy working at all, ever. Does it work if you set it globally?
I have seen setsockopt fail on kernels which do not support transparent proxy: IIRC you need to have a specific module loaded (ip_tproxy or something like that).

In short, I did have transparent working with previous versions, including 1.21 and this current version with transparent mode per protocol.

I just did a few tests. I changed the config to global transparent set to true and removed the protocol transparent lines. When I restarted the service, the capabilities listed in the service status screen showed an entry (where it did not show it with the protocol specific transparent on).

With the global transparent turned on, everything is working as expected. I changed the SSH to redirect to the same IP that is running SSLH and apache, for testing. The apache access logs are showing the correct client IP and the connection is completed properly to load the website. Here is the status screen: 

```
● sslh.service - SSL/SSH multiplexer
   Loaded: loaded (/lib/systemd/system/sslh.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2021-05-05 12:26:34 EDT; 4s ago
     Docs: man:sslh(8)
  Process: 11684 ExecStartPre=/usr/local/sbin/sslh-trans-enable.sh (code=exited, status=0/SUCCESS)
 Main PID: 11693 (sslh)
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/sslh.service
           ├─11693 /usr/sbin/sslh -F /etc/sslh.cfg
           └─11694 sslh: listener <SSLH IP>:https

May 05 12:26:34 sslh[11693]: ssh addr: <SSLH IP>:222. libwrap service: ssh log_level: 1 family 2 2 [] [fork] []
May 05 12:26:34 sslh[11693]: tls addr: <SSLH IP>:4443. libwrap service: https log_level: 1 family 2 2 [] [fork] []
May 05 12:26:34 sslh[11693]: timeout: 2
May 05 12:26:34 sslh[11693]: on-timeout: ssh
May 05 12:26:34 sslh[11693]: Listening to:
May 05 12:26:34 sslh[11693]: 3:        piWeb.gause3.lan:https        []
May 05 12:26:34 sslh[11693]: sslh-fork head-2021-05-04 started
May 05 12:26:34 sslh[11693]: sslh-fork head-2021-05-04 started
May 05 12:26:34 sslh[11693]: turning into sslh
May 05 12:26:34 sslh[11693]: capabilities: = cap_net_admin+ep
```

Here is when I remove the global and set both the SSH and TLS protocols with transparent true. For whatever reason, using the transparent setting in the protocol line removes the capabilities listed in the status screen. Not sure if this has something to do with the permissions issue with the `setsockopt IP_TRANSPARENT: Operation not permitted` error? The only difference in the config from above (working) to below (not working) is moving the global `transparent = true;` to the protocol specific `transparent = true;`

```
● sslh.service - SSL/SSH multiplexer
   Loaded: loaded (/lib/systemd/system/sslh.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2021-05-05 12:30:03 EDT; 2s ago
     Docs: man:sslh(8)
  Process: 11775 ExecStartPre=/usr/local/sbin/sslh-trans-enable.sh (code=exited, status=0/SUCCESS)
 Main PID: 11784 (sslh)
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/sslh.service
           ├─11784 /usr/sbin/sslh -F /etc/sslh.cfg
           └─11785 sslh: listener <SSLH IP>:https

May 05 12:30:03 sslh[11784]: ssh addr: <SSLH IP>:222. libwrap service: ssh log_level: 1 family 2 2 [] [fork] [transparent]
May 05 12:30:03 sslh[11784]: tls addr: <SSLH IP>:4443. libwrap service: https log_level: 1 family 2 2 [] [fork] [transparent]
May 05 12:30:03 sslh[11784]: timeout: 2
May 05 12:30:03 sslh[11784]: on-timeout: ssh
May 05 12:30:03 sslh[11784]: Listening to:
May 05 12:30:03 sslh[11784]: 3:        <SSLH IP>:https        []
May 05 12:30:03 sslh[11784]: sslh-fork head-2021-05-04 started
May 05 12:30:03 sslh[11784]: sslh-fork head-2021-05-04 started
May 05 12:30:03 sslh[11784]: turning into sslh
May 05 12:30:03 sslh[11784]: capabilities: =
```

Here is the config I used for testing:
```
verbose: 1;
foreground: true;
inetd: false;
numeric: false;
#transparent: true;
timeout: 2;
user: "sslh";
pidfile: "/var/run/sslh.pid";

listen:
(
    { host: "<sslh ip>"; port: "443"; }
);

protocols:
(
     { name: "ssh"; service: "ssh"; host: "<sslh ip>"; port: "222"; fork: true; transparent: true; },
     { name: "tls"; service: "https"; host: "<sslh ip>"; port: "4443"; fork: true; transparent: true; }
);
```

**Comment by SGNoc** [comment] 2021-05-05 16:56
Here are the sslh logs, if they help.

Global transparent = true;

```
May  5 12:26:34 systemd[1]: sslh.service: Succeeded.
May  5 12:26:34 sslh[11693]: ssh addr: <sslh IP>:222. libwrap service: ssh log_level: 1 family 2 2 [] [fork] []
May  5 12:26:34 sslh[11693]: tls addr: <sslh IP>:4443. libwrap service: https log_level: 1 family 2 2 [] [fork] []
May  5 12:26:34 sslh[11693]: timeout: 2
May  5 12:26:34 sslh[11693]: on-timeout: ssh
May  5 12:26:34 sslh[11693]: Listening to:
May  5 12:26:34 sslh[11693]: 3:#011<sslh IP>:https#011[]
May  5 12:26:34 sslh[11693]: sslh-fork head-2021-05-04 started
May  5 12:26:34 sslh[11693]: turning into sslh
May  5 12:26:34 sslh[11693]: capabilities: = cap_net_admin+ep
May  5 12:27:33 sslh[11693]: accepted fd 5
May  5 12:27:33 sslh[11693]: **** writing deferred on fd -1
May  5 12:27:33 sslh[11693]: probing for ssh
May  5 12:27:33 sslh[11693]: probed for ssh: PROBE_NEXT
May  5 12:27:33 sslh[11693]: probing for tls
May  5 12:27:33 sslh[11693]: probed for tls: PROBE_MATCH
May  5 12:27:33 sslh[11693]: connecting to <sslh IP>:4443 family 2 len 16
May  5 12:27:33 sslh[11693]: tls:connection from <client IP>:65228 to <sslh IP>:https forwarded from <client IP>:65228 to <sslh IP>:4443
May  5 12:27:33 sslh[11693]: flushing deferred data to fd 3
May  5 12:27:33 sslh[11693]: accepted fd 5
May  5 12:27:33 sslh[11693]: **** writing deferred on fd -1
```

Protocol transparent = true;

```
May  5 12:30:03 systemd[1]: sslh.service: Succeeded.
May  5 12:30:03 sslh[11784]: ssh addr: <sslh IP>:222. libwrap service: ssh log_level: 1 family 2 2 [] [fork] [transparent]
May  5 12:30:03 sslh[11784]: tls addr: <sslh IP>:4443. libwrap service: https log_level: 1 family 2 2 [] [fork] [transparent]
May  5 12:30:03 sslh[11784]: timeout: 2
May  5 12:30:03 sslh[11784]: on-timeout: ssh
May  5 12:30:03 sslh[11784]: Listening to:
May  5 12:30:03 sslh[11784]: 3:#011<sslh IP>:https#011[]
May  5 12:30:03 sslh[11784]: sslh-fork head-2021-05-04 started
May  5 12:30:03 sslh[11784]: turning into sslh
May  5 12:30:03 sslh[11784]: capabilities: =
May  5 12:30:58 sslh[11784]: accepted fd 5
May  5 12:30:58 sslh[11784]: **** writing deferred on fd -1
May  5 12:30:58 sslh[11784]: probing for ssh
May  5 12:30:58 sslh[11784]: probed for ssh: PROBE_NEXT
May  5 12:30:58 sslh[11784]: probing for tls
May  5 12:30:58 sslh[11784]: probed for tls: PROBE_MATCH
May  5 12:30:58 sslh[11784]: connecting to <sslh IP>:4443 family 2 len 16
May  5 12:30:58 sslh[11784]: common.c:270:setsockopt IP_TRANSPARENT: Operation not permitted
May  5 12:31:23 sslh[11784]: accepted fd 5
May  5 12:31:23 sslh[11784]: **** writing deferred on fd -1
```

**Comment by yrutschle** [comment] 2021-05-06 06:06
Thanks for the report -- per-protocol transparent setting must have never worked :-) the issue is common.c:set_capabilities(), which only looks at the global setting to decide whether to retain CAP_NET_ADMIN.

I'll fix that shortly probably over the weekend. Transparent proxy is always a bit of a stab in the dark for me as my server's kernel does not support it and I can't upgrade easily...

**Comment by SGNoc** [comment] 2021-05-06 15:57
I did some more digging, hopefully it helps. It looks like common.c:set_capabilities() is only called by common.c:drop_privileges(), which is only called by sslh-main.c if either the user or chroot variables are set in the config file.

I tested without using either user or chroot in my config and transparent is working. I tested with global transparent, and with per protocol transparent (with both TLS and SSH transparent true and also with TLS transparent true and SSH transparent false). It seems to be working properly in all of those cases.

The only instance it does not work is when user and/or chroot is set, which calls for the common.c:drop_privileges(), then common.c:set_capabilities(). I wasn't able to find a quick solution to change the `if (cfg.transparent)` line to also check for the per protocol transparent. The method didn't seem to have easy access to the cnx variable, like was used in common.c:connect_addr() with ` int transparent = cnx->proto->transparent || cfg.transparent;`.

I didn't dig in much more than that, but hopefully it will be an easy fix for you. Whenever you get the free time to look into it more and push out an update, I'll do some additional tests to check the transparent functionality, at least with TLS/SSH and possible OpenVPN (I don't have the services running to test more than that).

My network has my Apache server running in a segregated VLAN, so I use SSLH to redirect the SSH traffic to my other server running the SSH daemon, which is in a different VLAN. I never found a routing solution that worked to be able to keep the SSH connections with transparent and still working across VLANs. I don't think the dynamic routing is possible. But I still want my fail2ban to be functional with Apache, so I needed transparent for the TLS connections. My OpenVPN server is running on my router, so that will be next to test with/without transparent.

Thanks for the SSLH, it's a great solution for my network.

**Comment by yrutschle** [comment] 2021-05-08 05:46
This should be fixed in 905ac95ca1efa5935edcd600e1332ebc756620a3 (as mentionned, with limited testing...)

**Comment by SGNoc** [comment] 2021-05-08 20:46
Great, thanks for the quick fix! I just tested a variety of combinations:

Global transparent true, no protocol transparent options
Global transparent false, protocol transparent combinations of true/false for TLS and SSH (both true, both false, true false, false true)
No global transparent entry, protocol transparent combinations of true/false for TLS SSH (both true, both false, true false, false true)
No global transparent entry, protocol transparent combinations of true/false for TLS, SSH, and OpenVPN (T/T/T, T/T/F, T/F/T, T/F/T, F/T/T, F/T/F, F/F/T, F/F/F)

Everything with these combinations was working and I was able to verify my appropriate logs showed the proper client/server IPs where they were supposed to. Looks like everything is working for me on all of these combinations. Hope that helps for verification!

Thanks again!

**Comment by yrutschle** [comment] 2021-05-09 09:43
I see you're using sslh-fork -- if you're up for some more testing, I'd like to try something: have sslh-fork _always_ drop the capability after creating the connection. I have a suspicion that we can have sslh do:
- Retain CAP_NET_ADMIN if any protocol has transparent (the current behaviour)
- Accept a new connection; fork; probe the protocol
- setsockopt(transparent) if the probed protocol requires it
- Drop CAP_NET_ADMIN

Then you end up with a standalone process that has no capabilities. I'm ready to bet that the process only needs CAP_NET_ADMIN to call setsockopt(), but it is no longer required afterwards.

**Comment by yrutschle** [comment] 2021-05-09 13:49
Here, this is done in 8e130882fca93097f39972b0e720fa27d2d70094. Mind to have a test? I see the capability dropped an it works fine on my side, but without actual transparent proxying.

**Comment by SGNoc** [comment] 2021-05-10 01:57
Sure, I wasn't able to get to it today. I'll try to work on some testing tomorrow and get back with you on the results.

**Comment by yrutschle** [comment] 2021-05-11 04:42
excellent, thank you. I'll integrate CAP_NET_RAW right away then.

Capability drops are not logged, you can observe them with getpcaps(1).

**Closed by yrutschle** 2021-05-11 04:42 UTC
