### ISSUE TITLE
OpenVPN on port 443 behind HTTP Proxy

### ISSUE THREAD

**Issue by Belokan** [yrutschle/sslh#133] opened 2017-08-28 13:47 UTC
Hello all,

First thanks for this great piece of code !

I've been using OpenVPN for some time now hosted on a VM@home connected to DSL. Clients are mobile phones (Android), laptops (W10/Debian) and a Debian VM hosted on a PC behind an HTTP Proxy. As the VM hosting the OpenVPN server is as well serving apache proxy and sshd, I decided to "merge" those 3 services on the same 443 port.

I've configured sslh as follow:

`--user sslh --listen 192.168.1.221:443 --ssh 127.0.0.1:22 --ssl 127.0.0.1:2443 --openvpn 127.0.0.1:443`

I've changed apache's https port to 2443 including sites, I've changed OpenVPN from defaut 1194 to 443 and made some tests. No problem with phones and laptops, all 3 services are reachable. The problem is with the VM behind the Proxy and OpenVPN:

`OpenVPN Client(443) -> NAT(VirtualBOX) -> HTTP Proxy -> Internet -> NAT(router) -> sslh -> OpenVPN Server(443)`

Client side, I have obscure messages regarding packet length:

`WARNING: Bad encapsulated packet length from peer (21331), which must be > 0 and <= 1560 -- please ensure that --tun-mtu or --link-mtu is equal on both peers -- this condition could also indicate a possible active attack on the TCP link -- [Attempting restart...]`

But on server side, the message is more clear, when I use the VM's client, sslh treats the packets as "ssh":

`Aug 28 15:38:52 vmaccess sslh[457]: connection from xxx.xxx.xxx.xxx:63280 to vmaccess.home:https forwarded from localhost:47921 to localhost:ssh`

Instead of "https" on working clients (Android on LTE):

`Aug 28 15:39:08 vmaccess sslh[457]: connection from xxx.xxx.xxx.xxx:39977 to vmaccess.home:https forwarded from localhost:43301 to localhost:https`

Any idea about an option/solution server or client side in order to make it works ?
I have a second VM but connected to a LTE line I'd like to move to sslh too but I need it reachable on the VM behind the Proxy ...

Thanks in advance !

**Comment by Xiretza** [comment] 2017-10-06 15:21
I had this same issue, and for me it was caused by `timeout`being reached and consequently the packet being forwarded to ssh, as configured using `on-timeout`. Changing `timeout` to 5 fixed it. The real issue: timeout doesn't put anything special in the log, even in verbose mode!

**Comment by Belokan** [comment] 2017-10-09 05:34
You're a star Xiretza !
I've not replied before coming back to work and test your workaround (adding --timeout 5) and it works like a charm !

Thanks a lot and have a nice day.

**Comment by IceM4nn** [comment] 2017-12-17 03:40
Thank you @Xiretza !!!
Your solution helps me very much. Thanks a lot, have a nice day

**Comment by yrutschle** [comment] 2017-12-17 13:28
Ok, I'm closing this issue and adding a log message upon timeout, which is reasonable.

**Closed by yrutschle** 2017-12-17 13:28 UTC

**Comment by xkjdox** [comment] 2023-06-13 19:13
> I had this same issue, and for me it was caused by `timeout`being reached and consequently the packet being forwarded to ssh, as configured using `on-timeout`. Changing `timeout` to 5 fixed it.
> 
> The real issue: timeout doesn't put anything special in the log, even in verbose mode!

what on-timeout location mean

**Comment by xkjdox** [comment] 2023-06-13 19:25
> I had this same issue, and for me it was caused by `timeout`being reached and consequently the packet being forwarded to ssh, as configured using `on-timeout`. Changing `timeout` to 5 fixed it.
> 
> The real issue: timeout doesn't put anything special in the log, even in verbose mode!

where is location to put on-timeout ?

**Comment by yrutschle** [comment] 2023-06-15 20:19
`on-timeout` is a setting in the configuration file, to specify which protocol to connect to. If not set, `sslh` will connect to `ssh`. So if for example you have a very slow instance of OpenVPN, you could specify:
```
on-timeout: "openvpn";
```

See `example.cfg`.

**Comment by xkjdox** [comment] 2023-06-15 20:27
i still not understand, where should i put on-timeout: "openvpn";

i have a problem same like this when using sslh

this my config sslh
DAEMON_OPTS="--user sslh --listen 0.0.0.0:443 --ssh 127.0.0.1:22 --tls 127.0.0.1:1369 --openvpn 127.0.0.1:1194 --anyprot 127.0.0.1:109 --pidfile /var/run/sslh/sslh.pid"

**Comment by yrutschle** [comment] 2023-06-15 20:27
oh you're not using a configuration file. `sslh-fork --help` will list the available options, which are basically the same as what's in the config file so just add `--on-timeout='openvpn'` (or whatever you require) to your command line.
