### ISSUE TITLE
Very high CPU usage when running sslh

### ISSUE THREAD

**Issue by giovi321** [yrutschle/sslh#24] opened 2014-07-10 13:00 UTC
I asked on unix.stackexchange.com why this software was so prpcessor-intensive. This is the question and the very good answer I got, it seemsmto be a bug. Hope this helps.
http://unix.stackexchange.com/questions/141337/port-multiplexer-sslh-why-is-it-so-resource-intensive

**Comment by yotis1982** [comment] 2015-07-24 11:14
Hi,

I know it's pretty old, but I did hit the same problem:

-sslh running and having --ssl 127.0.0.1:443 directive
-no local webserver running to listen on 443
- high CPU usage and increasing logfile auth.log (couple of GB / day) because of the error mentioned above, which was logged.

However, what I discovered is that the high CPU usage had nothing to do with sslh in particular, but rather with fail2ban.
fail2ban is analyzing auth.log to catch fraudulent logins and to block them. As sslh was writing serveral lines per second on auth.log, fail2ban had a hard job to do, using the full CPU power to parse auth.log fail.

Removing the --ssl directive from sslh or bringing a nginx server up listening on 443 just for test, put an end to this problem.

Just my 2 cents on this.

**Comment by yrutschle** [comment] 2015-07-24 15:03
Hi,

Thanks for the feedback:

On Fri, Jul 24, 2015 at 04:14:55AM -0700, Calin Chiorean wrote:
> -sslh running and having --ssl 127.0.0.1:443 directive
> -no local webserver running to listen on 443
> - high CPU usage and increasing logfile auth.log (couple of GB / day) because of the error mentioned above, which was logged.

What message do you get in auth.log? I would expect sslh to
only connect (and log) once for each incoming connection it
tries to forward to localhost:443, not repeated logs.

Y.

**Comment by flowolf** [comment] 2015-07-27 15:02
I had the same issue today. I am using sslh version v1.13b on Raspbian.

/var/log/auth.log kept flooding with lines like these:
```
...
Jul 27 14:29:33 lou sslh[15327]: connection from localhost:49854 to localhost:https forwarded from localhost:49855 to localhost:https
Jul 27 14:29:33 lou sslh[15327]: connection from localhost:49855 to localhost:https forwarded from localhost:49856 to localhost:https
Jul 27 14:29:33 lou sslh[15327]: connection from localhost:49856 to localhost:https forwarded from localhost:49857 to localhost:https
Jul 27 14:29:33 lou sslh[15327]: connection from localhost:49857 to localhost:https forwarded from localhost:49858 to localhost:https
Jul 27 14:29:33 lou sslh[15327]: connection from localhost:49858 to localhost:https forwarded from localhost:49859 to localhost:https
Jul 27 14:29:33 lou sslh[15327]: connection from localhost:49859 to localhost:https forwarded from localhost:49860 to localhost:https
...
```
I used `--user sslh --listen 0.0.0.0:443 --ssh 127.0.0.1:22 --ssl 127.0.0.1:443 --pidfile /var/run/sslh/sslh.pid` as options. It seems to be an infinite self redirect. TCP connections stay open.

I finally used `--user sslh --listen X.Y.Z.X:443 --ssh 127.0.0.1:22 --ssl 127.0.0.1:443 --pidfile /var/run/sslh/sslh.pid` (X.Y.Z.X beeing my external listening IP) that stopped this behaviour and I got "connection refused"

**Additionally** when I run `sslh -F /etc/sslh.cfg -f` with the [basic.cfg](https://raw.githubusercontent.com/yrutschle/sslh/master/basic.cfg) I get a core dump.

**Comment by yotis1982** [comment] 2015-07-27 15:27
Hello

@yrutschle 

>What message do you get in auth.log? I would expect sslh to
>only connect (and log) once for each incoming connection it
>tries to forward to localhost:443, not repeated logs.

This was also strange to me. I had no connection to 443 and I did a tcpdump on the interface filtering on tcp 443, just to be sure that somebody out there is not trying some brute force / DoS on the port. There was nothing.

If needed I can reproduce this scenario.

**Comment by yrutschle** [comment] 2015-07-27 15:57
On Mon, Jul 27, 2015 at 08:02:26AM -0700, Florian wrote:
> I used `--user sslh --listen 0.0.0.0:443 --ssh 127.0.0.1:22 --ssl 127.0.0.1:443 --pidfile /var/run/sslh/sslh.pid` as options. It seems to be an infinite self redirect. TCP connections stay open.

This listens to all conections to port 443, and tries to
connect TLS connections to port 443... so as soon as a TLS
connection comes in, sslh tries to connect to itself... So
that's expectable :-)

> **Additionally** when I run `sslh -F /etc/sslh.cfg -f` with the [basic.cfg](https://raw.githubusercontent.com/yrutschle/sslh/master/basic.cfg) I get a core dump.

That's odd and definitely worth investigating; are you sure
you posted the correct link? this file uses my own server
name and wouldn't work anywhere else (unless your server is
also named thelonious, that is :-) ).

Y.

**Comment by yrutschle** [comment] 2015-07-27 16:03
On Mon, Jul 27, 2015 at 08:27:56AM -0700, Calin Chiorean wrote:
> >What message do you get in auth.log? I would expect sslh to
> >only connect (and log) once for each incoming connection it
> >tries to forward to localhost:443, not repeated logs.
> 
> This was also strange to me. I had no connection to 443 and I did a tcpdump on the interface filtering on tcp 443, just to be sure that somebody out there is not trying some brute force / DoS on the port. There was nothing.
> 
> If needed I can reproduce this scenario.

Yes please, I'd really be interested in getting to the
bottom of this, if you can be bothered trying it.

Was it sslh-fork or sslh-select? With select, I guess it's
possible some error condition is not handled properly and
results in one incoming connection remaining active. With
fork, I have no theory.

If you could run with --verbose --foreground and send both
the auth.log and the console output, that'd be of great
help.

**Comment by yotis1982** [comment] 2015-07-27 16:52
Hi,

I have limited time right now, but here is what I did until now. Also some background info.


>root@ng:~# cat /etc/lsb-release
>DISTRIB_ID=Ubuntu
>DISTRIB_RELEASE=14.04
>DISTRIB_CODENAME=trusty
>DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"

>root@ng:~# uname -a
>Linux ng 3.13.0-55-generic #94-Ubuntu SMP Thu Jun 18 00:27:10 UTC 2015 x86_64 x86_64 >x86_64 GNU/Linux

>root@ng:~# /usr/sbin/sslh -V
>sslh-fork 1.15

>DAEMON_OPTS="--user sslh --listen 0.0.0.0:443 --ssh 127.0.0.1:22 --pidfile /var/run/sslh/sslh.pid"

>root@ng:~# tail /var/log/auth.log
>Jul 27 18:33:45 ng sshd[26232]: Connection closed by 202.28.77.170 [preauth]
>Jul 27 19:04:44 ng sshd[1564]: Invalid user nameserver from 202.28.77.170
>Jul 27 19:04:44 ng sshd[1564]: input_userauth_request: invalid user nameserver [preauth]
>Jul 27 19:04:44 ng sshd[1564]: pam_unix(sshd:auth): check pass; user unknown
>Jul 27 19:04:44 ng sshd[1564]: pam_unix(sshd:auth): authentication failure; logname= uid=0 >euid=0 tty=ssh ruser= rhost=202.28.77.170
>Jul 27 19:04:46 ng sshd[1564]: Failed password for invalid user nameserver from 202.28.77.170 >port 29840 ssh2
>Jul 27 19:04:46 ng sshd[1564]: Connection closed by 202.28.77.170 [preauth]

CPU 
![cpu](https://cloud.githubusercontent.com/assets/1459159/8912012/1a30088e-3490-11e5-9c0c-b0b4c8067c26.PNG)


!
! After
!

>DAEMON_OPTS="--user sslh --listen 0.0.0.0:443 --ssh 127.0.0.1:22 --ssl 127.0.0.1:443 --pidfile >/var/run/sslh/sslh.pid"


>Jul 27 19:41:34 ng sslh[4395]: connection from localhost:59299 to localhost:https forwarded from >localhost:59300 to localhost:https
>Jul 27 19:41:34 ng sslh[4395]: connection from localhost:59300 to localhost:https forwarded from >localhost:59301 to localhost:https
>Jul 27 19:41:34 ng sslh[4395]: connection from localhost:59301 to localhost:https forwarded from >localhost:59302 to localhost:https
>Jul 27 19:41:34 ng sslh[4395]: connection from localhost:59302 to localhost:https forwarded from >localhost:59303 to localhost:https
>Jul 27 19:41:34 ng sslh[4395]: connection from localhost:59303 to localhost:https forwarded from >localhost:59304 to localhost:https
>Jul 27 19:41:35 ng sslh[4395]: connection from localhost:59304 to localhost:https forwarded from >localhost:59305 to localhost:https
>Jul 27 19:41:35 ng sslh[4395]: connection from localhost:59305 to localhost:https forwarded from >localhost:59306 to localhost:https
>Jul 27 19:42:19 ng sslh[4395]: connection from localhost:59306 to localhost:https forwarded from >localhost:59307 to localhost:https

CPU

![cpu1](https://cloud.githubusercontent.com/assets/1459159/8912028/35326e4c-3490-11e5-99c2-2c19066245d6.PNG)

After restarting the sslh with --ssl option, nothing was happening in the auth.log
Then I did open a browser and enter https://IP and the auth.log started to flood with the above information. I did close the browser, check on the eth for tcp 443 (nothing was coming in) but the text flood on auth.log contiune until had to stop the sslh daemon.

As said before the CPU in my case was exhausted by the fail2ban process which had to parse the auth.log file...

I'll update when I have a bit more time.

**Comment by yrutschle** [comment] 2015-07-27 17:05
On Mon, Jul 27, 2015 at 09:52:32AM -0700, Calin Chiorean wrote:
> >DAEMON_OPTS="--user sslh --listen 0.0.0.0:443 --ssh 127.0.0.1:22 --ssl 127.0.0.1:443 --pidfile >/var/run/sslh/sslh.pid"

Ok, same issue that Florian reported above: sslh listens to
all interfaces (0.0.0.0:443), so when browser connects to
port 443, sslh forwards to 127.0.0.1:443, which... sslh is
listening on.

> >Jul 27 19:41:34 ng sslh[4395]: connection from localhost:59299 to localhost:https forwarded from >localhost:59300 to localhost:https
> >Jul 27 19:41:34 ng sslh[4395]: connection from localhost:59300 to localhost:https forwarded from >localhost:59301 to localhost:https
> >Jul 27 19:41:34 ng sslh[4395]: connection from localhost:59301 to localhost:https forwarded from >localhost:59302 to localhost:https
> >Jul 27 19:41:34 ng sslh[4395]: connection from localhost:59302 to localhost:https forwarded from >localhost:59303 to localhost:https
> >Jul 27 19:41:34 ng sslh[4395]: connection from localhost:59303 to localhost:https forwarded from >localhost:59304 to localhost:https
> >Jul 27 19:41:35 ng sslh[4395]: connection from localhost:59304 to localhost:https forwarded from >localhost:59305 to localhost:https
> >Jul 27 19:41:35 ng sslh[4395]: connection from localhost:59305 to localhost:https forwarded from >localhost:59306 to localhost:https
> >Jul 27 19:42:19 ng sslh[4395]: connection from localhost:59306 to localhost:https forwarded from >localhost:59307 to localhost:https

And then it connects from port 59300, sslh forwards 59300 to
59301, then 59301 to 59302, and so on.


I'll try and think if it's possible for sslh to detect that
the configuration will create such a loop, or at least add a
caveat in the documentation.

Thanks for your time!

**Comment by flowolf** [comment] 2015-07-28 06:56
Hi,

> That's odd and definitely worth investigating; are you sure you posted the correct link? this file uses my own server name and wouldn't work anywhere else (unless your server is also named thelonious, that is :-) ).

The only thing I changed was the host "thelonious" to my FQDN.

but I got a core dump.

**Comment by hackeron** [comment] 2015-08-05 17:32
I'm seeing high CPU use also, I'm using like this:

```
/usr/sbin/sslh --foreground --user sslh --transparent --listen 0.0.0.0 443 --ssl 149.210.147.161 8443 --openvpn 149.210.147.161 7443 --pidfile /var/run/sslh/sslh.pid
```

Checking in top, when having around 10 connections per second sslh takes 9% cpu while Nginx is taking 6% -- why would sslh take more CPU than the web server serving the content?

**Comment by yrutschle** [comment] 2015-08-05 19:45
On Wed, Aug 05, 2015 at 10:32:07AM -0700, xanview wrote:
> ```
> /usr/sbin/sslh --foreground --user sslh --transparent --listen 0.0.0.0 443 --ssl 149.210.147.161 8443 --openvpn 149.210.147.161 7443 --pidfile /var/run/sslh/sslh.pid
> ```

Ah, my usual explanation doesn't apply here.

> Checking in top, when having around 10 connections per second sslh takes 9% cpu while Nginx is taking 6% -- why would sslh take more CPU than the web server serving the content?

What happens if you replace 0.0.0.0:443 with the list of
actual IP addresses? (I don't even have a theory at this
point, just shooting in the dark).

Y.

**Comment by SacredSkull** [comment] 2015-10-09 17:51
Can confirm the issue still exists. Personally I just changed the port that Nginx listened for SSL on to 444, and it works absolutely fine (obviously because no looping can occur). Was quite a shock seeing my syslog at 2GB :)

**Comment by yrutschle** [comment] 2015-10-12 21:02
Interestingly, ViKingIX's contribution to an entirely unrelated problem might help fix this one (if anyone wants to code it: using getifaddrs() (which lists all local addresses, see ViKingIX's code here: https://github.com/yrutschle/sslh/pull/69/files), fail at config time if forwarding to an address that's also listened to).

**Comment by rdebath** [comment] 2017-05-14 19:21
Just a tiny thing to add here, once the system gets into a loop the original connection can get torn down without the loop being broken. All it takes is for the time to make a connection being shorter than the time to drop a connection. The chain of connections will then extend until the connection time slows enough to match the disconnect time, at which time you'll have a persistent and stable list of `N` links with new connections being made at exactly the same speed as old ones are torn down because the caller has gone away.

It doesn't stop because if something (like new connections from the outside) does slow down the making of new connections for a while, the chain will get shorter. But once the load has gone the chain will stretch out again because connections are faster than disconnections.

So the best policy ... Don't let it happen, Don't overlap the listen addresses.

```
$ apt-get install bsdgames
$ /usr/games/worms -d 100
```

**Comment by tombii** [comment] 2019-03-22 09:52
Been a long time but just wanted to add that my case which I commented on back in 2014 was probably because sslh was feeding the connection back to itself, creating a loop since nothing was listening to port 443 except for sslh itself.

**Comment by yrutschle** [comment] 2020-05-29 20:01
I am closing this and logging #266  which sums it up. Not saying I'll implement this anytime soon :-)

**Closed by yrutschle** 2020-05-29 20:01 UTC
