### ISSUE TITLE
Fails to work on logging errors?

### ISSUE THREAD

**Issue by iamdoubz** [yrutschle/sslh#378] opened 2023-04-11 14:06 UTC
(Original title: tcp-listener.c:129:accept:24:Too many open files)

Hi again,

I have been running `sslh-ev v2.0-rc2-7-g842f6b0-dirty` for 4 days and now all of my traffic for new connections has stopped with the titled error.

1. Why is this happening?
2. How can I prevent it?
3. What can I do here?

**Comment by licaon-kter** [comment] 2023-04-11 14:18
Search for `linux too many open files` on the internet :)

**Comment by iamdoubz** [comment] 2023-04-11 14:22
Actually figured it out..... my `sslh.log` file was... 135G... and filled up my hard drive................. woops

**Comment by yrutschle** [comment] 2023-04-11 19:27
I am always so happy when it's not my fault :laughing: 

that said, arguably in your situation sslh should just keep on working, just without logging, so there might be something to investigate -- I'll reopen (I can't investigate right now but don't want to lose track of it).

**Comment by yrutschle** [comment] 2024-03-24 21:17
ok, I just investigated:
- preventing `sslh` from writing to files at all (with `ulimit -f 0`) won´t stop it
- logging functions do not return any values, so log failure has no effect (theoritically).
So my guess is: because sslh.log filled the disk, *other* processes started pausing on writes, which resulted in an increasing number of opened files, which affected `sslh`'s capacity to accept and process ew connections (as each connection uses 2 file descriptors) (this part is actually working as intended: if we can´t accept() or connect(), we drop the connection while keeping working). So really not related to our logging at all.

I'll close this as "unrelated to sslh", then :)   Feel free to reopen if new information turns up.

**Closed by yrutschle** 2024-03-24 21:17 UTC
