### ISSUE TITLE
Openvpn + HTTP proxy

### ISSUE THREAD

**Issue by Yamakaky** [yrutschle/sslh#43] opened 2015-02-23 14:02 UTC
When using an HTTP proxy to contact an openvpn server, the packets are accounted as http ones, and not openvpn. So in the protocol section, I had to point http to the openvpn port. It's the expected behavior, but I have searched for a solution for 2 months ^^ You should add a note in the README to help the others users. I use it on port 443, so redirecting http on this port should not be a problem.

**Comment by yrutschle** [comment] 2015-02-23 14:09
On Mon, Feb 23, 2015 at 06:02:54AM -0800, Yamakaky wrote:
> When using an HTTP proxy to contact an openvpn server, the packets are accounted as http ones, and not openvpn. So in the protocol section, I had to point http to the openvpn port. It's the expected behavior, but I have searched for a solution for 2 months ^^ You should add a note in the README to help the others users. I use it on port 443, so redirecting http on this port should not be a problem.

This sounds interesting, but confusing. What are you doing?

This:?
OpenVPN client ---> HTTP proxy ---internet---> sslh ---> OpenVPN

And then, do you mean you had to set sslh to forward HTTP to
OpenVPN, e.g.:

sslh --http localhost:openvpn --ssh localhost:ssh
?

Cheers,
Y.

**Comment by Yamakaky** [comment] 2015-02-23 15:40
It is what I want. For now, I just put openvpn directly on the 443 port, without. I will try to make sslh work with this setup.

**Comment by yrutschle** [comment] 2015-02-23 16:10
On Mon, Feb 23, 2015 at 07:40:58AM -0800, Yamakaky wrote:
> It is what I want. For now, I just put openvpn directly on the 443 port, without. I will try to make sslh work with this setup.

I would expect proxytunnel to be able to encapsulate the
OpenVPN traffic through the HTTP Proxy.

There is actually an example of  something similar in the
README, you might want to check it out.

**Comment by Yamakaky** [comment] 2015-02-23 16:23
Maybe I didn't explain well : the proxy is run by my school on the wifi network. Openvpn has an option like httptunnel but builtin.

**Comment by Yamakaky** [comment] 2015-02-24 13:59
I tried to forward http + openvpn to the openvpn port, but it still doesn't work at school with the proxy. Back to openvpn on 443...

**Comment by GibbsFrance** [comment] 2015-03-03 13:52
Hi,

I have the same problem, but when I forward ssl to openvpn port, the issue is resolved. (I use http-proxy in my client config for use proxy of my university).

Have a nice day.

**Comment by Yamakaky** [comment] 2015-03-03 14:05
Of course, it's ssl... So @yrutschle, please update the readme to help the others users.

**Comment by yrutschle** [comment] 2015-03-03 14:35
I'm happy to update documentation, but I can't say that I
have understood the issue at all. It's still unclear to me
what it is you were trying to do, and I have no idea what
you did to get "it" to work now.

**Comment by GibbsFrance** [comment] 2015-03-03 15:14
The problem is that when the OpenVPN traffic passes through a proxy (like a school, company, ...), the server will receive the packet and sslh probe that will process this packet will be "ssl" probe and not "openvpn" probe.

So the problem comes from the passage of traffic through a proxy. I do not know if this can be fixed in sslh. Even by updating the documentation, it probably will not arrange users because it prevents having a HTTPS traffic and OpenVPN traffic simultaneously (as to solve the problem, we must put the ssl probe to the same port of OpenVPN probe).

**Comment by yrutschle** [comment] 2015-03-03 15:43
This would be highly dependant on the kind of proxy.
Transparent proxies would not do that. Non-transparent
proxies require SSL encapsulation indeed (using e.g.
proxytunnel or corkscrew), but that's already
explained in the README.

**Comment by Yamakaky** [comment] 2015-03-03 17:37
Maybe put sslh on port 80 ?

**Comment by yrutschle** [comment] 2016-01-22 14:55
Closing because of lack of further comments.

**Closed by yrutschle** 2016-01-22 14:55 UTC

**Comment by jbwdevries** [comment] 2016-02-11 12:26
I had the same problem, but I couldn't forward HTTPS traffic to OpenVPN. But when I switched the order so OpenVPN was first (on command line or in config file), OpenVPN over HTTP tunnel went through properly (tested with 1.15).

**Comment by Yamakaky** [comment] 2016-02-11 13:07
You mean openvpn then http then ssl?

**Comment by jbwdevries** [comment] 2016-02-11 15:00
I didn't have http but yes. This enables OpenVPN with and without HTTP proxy:

    sslh --openvpn $IPADDR:11194 --ssl $IPADDR:11443

If you do it the other way around:

    sslh --ssl $IPADDR:11443 --openvpn $IPADDR:11194 

Then OpenVPN over HTTP proxy's connections end up at your webserver, and you get

    WARNING: Bad encapsulated packet length from peer

In your OpenVPN logs.

**Comment by Yamakaky** [comment] 2016-02-11 16:02
Strange. I didn't try recently, but with 
```
protocols:
(
     { name: "http"; host: "ns342653"; port: "880"; probe: "builtin" },
     { name: "ssh"; host: "ns342653"; port: "1234"; probe: "builtin" },
     { name: "openvpn"; host: "ns342653"; port: "1194"; probe: "builtin" },
     { name: "ssl"; host: "ns342653"; port: "1194"; probe: "builtin" }
     #{ name: "xmpp"; host: "ns342653"; port: "5222"; probe: "builtin" },
);
```
it failed

**Comment by Yamakaky** [comment] 2016-09-24 14:44
Stranger: it works now!
