### ISSUE TITLE
Publish an official Docker image

### ISSUE THREAD

**Issue by alecsg77** [yrutschle/sslh#334] opened 2022-06-09 15:22 UTC
There are a few unofficial Docker images.
I just forked to create yet another unofficial Docker image.
What about having an official Docker image published in DockerHub or in GitHub Packages?
I'm not sure if there is a CI/CD pipeline already in place on a server or service to publishing other artifacts like RPM or DEB packages.

**Comment by yrutschle** [comment] 2023-06-05 18:56
Closed in 7b7c9231b0018787ab3c926386e0b359d03862eb

**Comment by oliv3r** [comment] 2023-06-05 20:07
@yrutschle the issue is still open ;)

**Closed** 2023-06-10 19:25 UTC
