### ISSUE TITLE
Can't establish a https connection through sslh with curl

### ISSUE THREAD

**Issue by zingmars** [yrutschle/sslh#189] opened 2018-06-27 09:39 UTC
With sslh (with transparent proxying enabled) present everything seems to work fine (can ssh, can access https over browser etc) until I try to curl (or wget) the website from a linux terminal. The received error messages vary, but in short, the TLS connection always times out (it works just fine when a connection to a direct port is attempted).

```
user@PC:~$ curl -v -I https://site
*   Trying IP...
* Connected to site (IP) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 592 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* gnutls_handshake() failed: An unexpected TLS packet was received.
* Closing connection 0
curl: (35) gnutls_handshake() failed: An unexpected TLS packet was received.
```

```
user@anotherPC:/# curl -v -I https://site
* Rebuilt URL to: https://site/
*   Trying IP...
* Connected to site (IP) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 593 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* gnutls_handshake() failed: The TLS connection was non-properly terminated.
* Closing connection 0
curl: (35) gnutls_handshake() failed: The TLS connection was non-properly terminated.
```

```
user@yetAnotherPC:~# curl -I https://site/ -v
*   Trying IP...
* TCP_NODELAY set
* Connected to site (IP) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to site:443
* stopped the pause stream!
* Closing connection 0
```

Meanwhile, on a port without sslh serving the same virtualhost entry - 
```
user@yetAnotherPC:~# curl -I https://site:444 -v
*   Trying IP...
* TCP_NODELAY set
* Connected to site (IP) port 444 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=site
*  start date: May  1 03:00:41 2018 GMT
*  expire date: Jul 30 03:00:41 2018 GMT
*  subjectAltName: host "site" matched cert's "site"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x1d18fb0)
( returned headers were removed for brevity )
```

I'm running it on Ubuntu 18.04 with `DAEMON_OPTS="--user sslh --listen IP:443 --ssh local-nonloopback-IP:22 --ssl local-nonloopback-IP:443 --pidfile /var/run/sslh/sslh.pid --transparent`. 

When making a connection from curl this appears in logs - 

```
Jun 27 11:42:59 server sslh[13119]: ssl:connection from remoteIP:10557 to server-fqdn:https forwarded from remoteIP:10557 to local-nonloopback-IP:https
Jun 27 11:45:06 server sslh[13119]: forward to ssl failed:connect: Connection timed out
Jun 27 11:45:06 server sslh[13119]: connect: Connection timed out
```

Works just fine when connecting from a web browser. Sites with cloudflare's reverse proxy protection also work as they should.

**Comment by yrutschle** [comment] 2018-06-28 13:57
On Wed, Jun 27, 2018 at 09:39:41AM +0000, Ingmars Melkis wrote:
> With sslh [..] everything seems to work fine [...] until I try to curl (or wget) 


I just tried connecting with curl, it seems to work fine for
me.

If both curl and wget don't work, I'd tend to suspect a
problem on the client side: are you behind a corporate
proxy? Maybe you set it up for your browser and ssh, but not
curl and wget?

When connecting, what happens on the sslh side? (try with
sslh -v -f) Do you see the incoming connexion?


Y.

**Comment by Zibri** [comment] 2018-12-10 09:22
how did you fix docker rules?

**Comment by rrschmidt** [comment] 2019-07-16 07:56
Please reopen. We can reproduce exactly the same issue on our production environment and it seems also to affect connections that come from normal browsers. 

Key factors to reproduce the issue: 
- the issue gets active when we have about ~14,000 connections running through sslh ... if there are fewer connections there are no problems
- but even when the issue is active some requests come through, our curl based nagios checks are constantly flapping then
- it not only affects curl based requests, but also our webapp that is running https and wss through the sslh
- the issue seems to be correlated to our upgrade from openssl 1.1.0 to openssl 1.1.1 ... one day later the issue started to appear

**Comment by yrutschle** [comment] 2019-07-16 13:00
This sounds like a different issue though, as it's not linked to curl specifically.

So:
- Large number of connections: is this sslh-fork or sslh-select? How does it behave with the other one?
- Can you run sslh with verbose and paste logs when the issue happens?
- Can't think how openssl version would come into play... Does it work if you remove sslh and connect directly to your Web server?

**Comment by rrschmidt** [comment] 2019-07-16 13:21
Thank you for your quick reply. Yes, at least the title of this issue isn't a good match anymore, but the symptoms are the same. 

Concerning your questions: 
1. we're using sslh-fork for historical reasons, believe there was a problem with sslh-select. As these are production systems there's no easy path for testing, will see what can be done. 
2. switching logs to verbose will be bit tricky, too as we're only able to reproduce it on a production system
3. when accessing the nginx behind it, things run smoothly, means sslh is very likely the source of the problem. My best guess is that OpenSSL 1.1.1 introduced some new features that cause confusion, although it is strange that the problem only pops up at a certain amount of connections

**Comment by yrutschle** [comment] 2019-07-16 16:08
sslh-fork should be about rock-solid, it's very simple.
Things I can think off that could go wrong:
- Too many PIDs and fork fails (I'd expect that to produce logs), which would indeed result in dropping connections
- Too many... file descriptors on the whole system, this would result in socket() or connect() calls failing (I'd expect that to produce logs as well)
- Some other resource limit is hit...

How do you estimate the 14000 connections? It's so close to 16000 which would be 32k / 2 :)

I still can't think how OpenSSL would play a role here, except maybe using more resources (like, more file descriptors?). Thing is, sslh does not use OpenSSL at all.

**Comment by yrutschle** [comment] 2019-07-16 16:12
(I'm closing this again and vaguely moving the discussion under a new issue. I hoped to be able to just move the posts, but apparently that isn't possible)

**Closed by yrutschle** 2019-07-16 16:12 UTC
